ALTER TABLE character_table DROP FOREIGN KEY FK_CHARACTER_ON_FIGHT;
ALTER TABLE character_table DROP COLUMN fight_id;

ALTER TABLE occupation ADD fight_id BIGINT NOT NULL;
ALTER TABLE occupation ADD CONSTRAINT FK_OCCUPATION_ON_FIGHT FOREIGN KEY (fight_id) REFERENCES fight (id);

ALTER TABLE fight ADD is_active BIT(1) NOT NULL;
