openapi: 3.0.0
info:
  title: RPG API
  description: API for RPG REST game.
  version: '0.1'
paths:
  /users:
    get:
      summary: Returns a list of users.
      x-preauth: "hasAuthority('ADMIN')"
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLite'
components:
  schemas:
    UserLite:
      type: object
      required:
        - userName
        - email
      properties:
        userName:
          type: string
        email:
          type: string