spring:
  config:
    import: classpath:credentials.yml
  datasource:
    password: 'zaq1@WSX3'
    username: root
    url: jdbc:mysql://localhost:3306/rest_rpg?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    database: mysql
  mail:
    host: ${mock-mail.host}
    port: ${mock-mail.port}
    username: ${mock-mail.username}
    password: ${mock-mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-message: always
token:
  refreshTokenExpirationMs: '604800000'
  accessTokenExpirationMs: '86400000'
  refreshTokenCookieName: jwt
logging.level.org.springframework.security: DEBUG
