spring:
  datasource:
    password: 'zaq1@WSX3'
    username: root
    url: jdbc:mysql://localhost:3306/rest_rpg?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
token:
  refreshTokenExpirationMs: '604800000'
  accessTokenExpirationMs: '900000'
  refreshTokenCookieName: jwt
  secretKey: 5267556B58703273357638792F423F4528482B4D6251655368566D5971337436
logging.level.org.springframework.security: DEBUG
